"""empty message

Revision ID: 75afb8bb3cb6
Revises: 
Create Date: 2022-05-01 12:41:51.616373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75afb8bb3cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea', sa.String(length=400), nullable=True),
    sa.Column('team', sa.String(length=400), nullable=True),
    sa.Column('contact', sa.String(length=400), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_title'), 'upload', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_title'), table_name='upload')
    op.drop_table('upload')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
